In [71]:
import pandas as pd
import numpy as np
import csv

In [76]:
df_abalone = pd.read_csv("데이터셋/abalone.csv")
df_abalone.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [77]:
df_abalone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [78]:
def main_excute(epoch_count = 10, mb_size = 2, report = 2, train_ratio = 0.8):
    load_dataset()
    weight_initial, bias_initial = init_param()
    losses_mean_row, accs_mean_row, final_acc = train_and_test(epoch_count,mb_size, report, train_ratio)
    
    return weight_initial, bias_initial, losses_mean_row, accs_mean_row, final_acc

In [79]:
def load_dataset():
    with open('데이터셋/abalone.csv') as csvfile:
        csvreader = csv.reader(csvfile)
        next(csvreader)
        rows = []
        for row in csvreader:
            rows.append(row)

    global data, input_cnt, output_cnt 
    
    input_cnt, output_cnt = 10, 1
    data = np.zeros([len(rows), input_cnt + output_cnt])

    for n, row in enumerate(rows):
        if row[0] == 'M' : data[n, 0] = 1
        if row[0] == 'F' : data[n, 1] = 1
        if row[0] == 'I' : data[n, 2] = 1
        data[n, 3 : ]= row[1:]

In [81]:
%run MathUtils.ipynb

In [83]:
load_dataset()
print(data)

[[ 1.      0.      0.     ...  0.101   0.15   15.    ]
 [ 1.      0.      0.     ...  0.0485  0.07    7.    ]
 [ 0.      1.      0.     ...  0.1415  0.21    9.    ]
 ...
 [ 1.      0.      0.     ...  0.2875  0.308   9.    ]
 [ 0.      1.      0.     ...  0.261   0.296  10.    ]
 [ 1.      0.      0.     ...  0.3765  0.495  12.    ]]


In [84]:
def init_param():
    global weight, bias
    weight_initial = []
    bias_initial = []
    weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
    bias = np.zeros([output_cnt])
    print("initial Weight Value: \n{}".format(weight))
    print("initial Bias Value: \n{}".format(bias))
    weight_initial.append(weight)
    bias_initial.append(bias)
    
    return weight_initial, bias_initial

In [85]:
weight_initial, bias_initial = init_param()

initial Weight Value: 
[[ 0.07865762]
 [-0.06150392]
 [-0.01501127]
 [ 0.00725753]
 [-0.01338488]
 [-0.02813899]
 [-0.0011171 ]
 [ 0.01609468]
 [ 0.02013071]
 [-0.0329204 ]]
initial Bias Value: 
[0.]


In [86]:
def train_and_test(epoch_count, mb_size, report, train_ratio):
    pass

In [87]:
mb_size = 2
train_ratio = 0.8
print(data.shape)

(4177, 11)


In [89]:
def arrange_data(mb_size, train_ratio):
    
    global shuffle_map, test_begin_index
    
    shuffle_map = np.arange(data.shape[0])
    np.random.shuffle(shuffle_map)
    
    mini_batch_step_count = int(data.shape[0]*train_ratio) // mb_size
    test_begin_index = mini_batch_step_count * mb_size
    return mini_batch_step_count

In [90]:
mini_batch_step_count = arrange_data(mb_size=2, train_ratio=0.8)
print("mini_batch_step_count:", mini_batch_step_count)
print("shuffle_map : ",shuffle_map[:2])
print("test_begin_index : ", test_begin_index)

mini_batch_step_count: 1670
shuffle_map :  [3885  921]
test_begin_index :  3340


In [91]:
def get_test_data():
    test_data = data[shuffle_map[test_begin_index:]]
    return test_data[:, : - output_cnt], test_data[:, -output_cnt: ]

In [92]:
test_x, test_y = get_test_data()
print(test_x)
print("===========================================")
print(test_y)

[[0.     1.     0.     ... 0.513  0.301  0.305 ]
 [0.     1.     0.     ... 0.7365 0.3055 0.37  ]
 [1.     0.     0.     ... 0.2405 0.127  0.139 ]
 ...
 [1.     0.     0.     ... 0.5785 0.3125 0.384 ]
 [1.     0.     0.     ... 0.4215 0.2255 0.227 ]
 [1.     0.     0.     ... 0.3495 0.2185 0.275 ]]
[[10.]
 [ 9.]
 [ 8.]
 [ 9.]
 [11.]
 [14.]
 [13.]
 [13.]
 [ 7.]
 [10.]
 [16.]
 [ 9.]
 [10.]
 [ 9.]
 [ 9.]
 [ 7.]
 [11.]
 [ 6.]
 [12.]
 [ 9.]
 [21.]
 [14.]
 [ 7.]
 [ 6.]
 [12.]
 [15.]
 [10.]
 [ 7.]
 [10.]
 [ 7.]
 [ 6.]
 [ 8.]
 [ 7.]
 [11.]
 [10.]
 [ 9.]
 [ 7.]
 [ 9.]
 [ 8.]
 [14.]
 [15.]
 [ 8.]
 [ 8.]
 [13.]
 [ 9.]
 [ 8.]
 [12.]
 [ 6.]
 [ 9.]
 [11.]
 [10.]
 [ 9.]
 [ 7.]
 [ 8.]
 [11.]
 [13.]
 [11.]
 [10.]
 [12.]
 [10.]
 [ 7.]
 [ 6.]
 [ 8.]
 [11.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 6.]
 [ 8.]
 [10.]
 [10.]
 [ 9.]
 [ 9.]
 [12.]
 [ 7.]
 [13.]
 [ 8.]
 [ 7.]
 [12.]
 [10.]
 [14.]
 [10.]
 [16.]
 [11.]
 [10.]
 [ 7.]
 [ 8.]
 [14.]
 [11.]
 [11.]
 [11.]
 [11.]
 [15.]
 [ 8.]
 [ 9.]
 [ 6.]
 [12.]
 [ 5.]
 [ 7.]
 [ 4.]


In [93]:
def get_train_data(mb_size, n):
    if n == 0:
        np.random.shuffle(shuffle_map[:test_begin_index])
        
    train_data = data[shuffle_map[mb_size * n : mb_size*(n+1)]]
    
    return train_data[:, :-output_cnt], train_data[:, -output_cnt :]
    

In [95]:
train_x, train_y = get_train_data(mb_size = 2, n = 0)
print(train_x)
print("=============================")
print(train_y)

[[0.     1.     0.     0.515  0.375  0.11   0.6065 0.3005 0.131  0.15  ]
 [0.     0.     1.     0.285  0.205  0.07   0.106  0.039  0.0285 0.034 ]]
[[6.]
 [5.]]


In [96]:
def run_test(x, y):
    accuracy = 100
    return accuracy
run_test(0,0)

100

In [97]:
def run_train(x, y):
    loss = 0
    accuracy = 95
    return loss, accuracy
run_train(0,0)

(0, 95)

In [98]:
def train_and_test(epoch_count, mb_size, report, train_ratio):
    mini_batch_step_count = arrange_data(mb_size, train_ratio)
    test_x, test_y = get_test_data()
    
    losses_mean_row = []
    accs_mean_row = []
    
    for epoch in range(epoch_count):
        losses = []
        accs = []
        for n in range(mini_batch_step_count):
            train_x, train_y = get_train_data(mb_size, n)
            loss, acc = run_train(train_x, train_y)
            losses.append(loss)
            accs.append(acc)
            
        if report >0 and (epoch +1)% report == 0:
            acc = run_test(test_x, test_y)
            print("Epoch {} : Train - Loss = {:.3f}, Accuracy = {:.3f}  / Test - Accuracy = {:.3f}".\
                  format(epoch + 1, np.mean(losses), np.mean(accs), acc))
            
        losses_mean = np.mean(losses)
        accs_mean = np.mean(accs)*100
        
    final_acc = run_test(test_x, test_y)
    print("=" * 30, "Final TEST", "=" * 30)
    print("\nFinal Accuracy : {:.3f}".format(final_acc))
    
    return losses_mean, accs_mean, final_acc


In [99]:
result = train_and_test(epoch_count=10, mb_size=2, report = 3, train_ratio=0.8)

Epoch 3 : Train - Loss = 0.000, Accuracy = 95.000  / Test - Accuracy = 100.000
Epoch 6 : Train - Loss = 0.000, Accuracy = 95.000  / Test - Accuracy = 100.000
Epoch 9 : Train - Loss = 0.000, Accuracy = 95.000  / Test - Accuracy = 100.000
============================== Final TEST ==============================

Final Accuracy : 100.000


In [100]:
def forward_neuralnet(x):
    y_hat = np.matmul(x, weight) + bias
    return y_hat, x

In [107]:
y_hat, _ = forward_neuralnet(train_x)
print("y_hat : \n", y_hat)
print(y_hat.shape)

y_hat : 
 [[-0.06402292]
 [-0.01769279]]
(2, 1)


In [108]:
def forward_postproc(y_hat, y):
    diff = y_hat - y
    square = np.square(diff)
    loss = np.mean(square)
    
    return loss, diff

In [109]:
train_y

array([[6.],
       [5.]])

In [111]:
loss, _ = forward_postproc(y_hat, train_y)
print(loss)

30.97480745361902


In [112]:
# 평가
def eval_accuracy(y_hat, y):
    mdiff = np.mean(np.abs((y_hat-y) / y))
    return 1 - mdiff

In [113]:
acc = eval_accuracy(y_hat, train_y)
print("Acc : {}".format(np.round(acc*100,3)))

Acc : -0.71
