In [62]:
import pandas as pd
import numpy as np
import csv
df_abalone = pd.read_csv('데이터셋/abalone_mini.csv')
df_abalone.describe()

0.455     0.365     0.095     0.514    0.2245     0.101      0.15  \
count  4.000000  4.000000  4.000000  4.000000  4.000000  4.000000  4.000000   
mean   0.412500  0.326250  0.107500  0.405875  0.165250  0.085875  0.122500   
std    0.091788  0.079831  0.026615  0.229871  0.083492  0.049775  0.073087   
min    0.330000  0.255000  0.080000  0.205000  0.089500  0.039500  0.055000   
25%    0.345000  0.262500  0.087500  0.220375  0.097000  0.046250  0.066250   
50%    0.395000  0.315000  0.107500  0.370750  0.157500  0.081250  0.112500   
75%    0.462500  0.378750  0.127500  0.556250  0.225750  0.120875  0.168750   
max    0.530000  0.420000  0.135000  0.677000  0.256500  0.141500  0.210000   

          15  
count   4.00  
mean    8.25  
std     1.50  
min     7.00  
25%     7.00  
50%     8.00  
75%     9.25  
max    10.00

In [63]:
def main_execute(epoch_coun = 10, mb_size = 10, report = 2, train_ratio = 0.8):
    load_dataset()
    weight_initial, bias_initial = init_param()
    losses_mean_row, accs_mean_row, final_acc = train_and_test(epoch_count, mb_size, report, train_ratio)
    return weight_initial, bias_initial, losses_mean_row, accs_mean_row, final_acc

In [64]:
def load_dataset():
    with open('데이터셋/abalone_mini.csv')as csvfile:
        csvreader = csv.reader(csvfile)
        next(csvreader)
        rows = []
        
        for row in csvreader:
            rows.append(row)
            
    global data, input_cnt, output_cnt
    
    input_cnt, output_cnt = 10, 1
    data = np.zeros([len(rows), input_cnt + output_cnt])
    
    for n,row in enumerate(rows):
        if row[0] == 'M': data[n,0] = 1
        if row[0] == 'F': data[n,1] = 1
        if row[0] == 'I': data[n,2] = 1
        data[n, 3: ] = row[1:]

In [65]:
load_dataset()

In [66]:
%run MathUtils.ipynb

In [67]:
def init_param():
    global weight, bias
    
    weight_initial =[]
    bias_initial =[]
    weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
    bias = np.zeros([output_cnt])
    print(f"initial Weight Value : \n{weight}")
    print(f'initial Bias Value : \n{bias}')
    weight_initial.append(weight)
    bias_initial.append(bias)
    
    return weight_initial, bias_initial

In [68]:
weight_initial, bias_initial = init_param()

initial Weight Value : 
[[-0.04931623]
 [-0.02197562]
 [ 0.0201902 ]
 [-0.00872151]
 [-0.00141418]
 [-0.01390358]
 [ 0.00808063]
 [ 0.00208285]
 [-0.03898588]
 [-0.01539986]]
initial Bias Value : 
[0.]


In [69]:
def train_and_test(epoch_count, mb_size, report, train_ratio):
    pass

In [70]:
mb_size = 2
train_ratio = 0.8
print(data.shape)

(4, 11)


In [71]:
def arrange_data(mb_size, train_ratio):
    global shuffle_map, test_begin_index
    
    shuffle_map = np.arange(data.shape[0])
    
    np.random.shuffle(shuffle_map)
    
    mini_batch_step_count = int(data.shape[0] * train_ratio)//mb_size
    
    test_begin_index = mini_batch_step_count * mb_size
    
    return mini_batch_step_count

In [72]:
mini_batch_step_count = arrange_data(mb_size=2, train_ratio=0.8)
print("mini_batch_step_count:", mini_batch_step_count)
print("shuffle_map:", shuffle_map[:5])
print("test_begin_index:", test_begin_index)

mini_batch_step_count: 1
shuffle_map: [0 3 1 2]
test_begin_index: 2


In [73]:
def get_test_data():
    test_data = data[shuffle_map[test_begin_index:]]
    return test_data[:, :-output_cnt], test_data[:,-output_cnt:]

In [74]:
test_x, test_y = get_test_data()
print(test_x[:10])
print("=======================")
print(test_y[:10])

[[0.     1.     0.     0.53   0.42   0.135  0.677  0.2565 0.1415 0.21  ]
 [1.     0.     0.     0.44   0.365  0.125  0.516  0.2155 0.114  0.155 ]]
[[ 9.]
 [10.]]


In [75]:
# nth :  미니배치 덩어리의 횟수
def get_train_data(mb_size, nth):
    if nth == 0:
        np.random.shuffle(shuffle_map[:test_begin_index])
        
    train_data = data[shuffle_map[mb_size * nth : mb_size * (nth + 1)]]
    
    return train_data[:, :-output_cnt], train_data[:, -output_cnt:]

In [76]:
train_x, train_y = get_train_data(mb_size = 10, nth = 0)
print(train_x)
print("===================")
print(train_y)

[[1.     0.     0.     0.35   0.265  0.09   0.2255 0.0995 0.0485 0.07  ]
 [0.     0.     1.     0.33   0.255  0.08   0.205  0.0895 0.0395 0.055 ]
 [0.     1.     0.     0.53   0.42   0.135  0.677  0.2565 0.1415 0.21  ]
 [1.     0.     0.     0.44   0.365  0.125  0.516  0.2155 0.114  0.155 ]]
[[ 7.]
 [ 7.]
 [ 9.]
 [10.]]


In [77]:
def run_test(x,y):
    accuracy = 100
    return accuracy
run_test(0,0)

100

In [78]:
def run_train(x, y):
    loss = 0
    accuracy = 95
    return loss, accuracy

run_train(0,0)

(0, 95)

In [94]:
def train_and_test(epoch_count, mb_size, report, train_ratio):
    mini_batch_step_count = arrange_data(mb_size, train_ratio)
    
    test_x, test_y = get_test_data()
    
    losses_mean_row = []
    accs_mean_row = []
    
    for epoch in range(epoch_count):
        losses = []
        accs = []
        for n in range(mini_batch_step_count):
            train_x, train_y = get_train_data(mb_size, n)
            
            loss, acc = run_train(train_x, train_y)
            
            losses.append(loss)
            accs.append(acc)
            
        if report > 0 and (epoch+1)%report == 0:
            acc = run_test(test_x, test_y)
            print(f"Epoch{epoch+1}: Train - Loss = {np.mean(losses):.3f}, Accuracy = {np.mean(accs):.3f}/Test - Accuracy = {acc:.3f}")

        losses_mean = np.mean(losses)
        accs_mean = np.mean(accs) * 100

        losses_mean_row.append(losses_mean)
        accs_mean_row.append(accs_mean)
    
    final_acc = run_test(test_x, test_y)
    print("="*30,'Final_TEST','='*30)
    print(f"\n Final Accuracy: {final_acc:.3f}")

    return losses_mean_row, accs_mean_row, final_acc

In [95]:
def forward_neuralnet(x):
    y_hat = np.matmul(x, weight) + bias
    return y_hat

In [96]:
y_hat = forward_neuralnet(train_x)
print(y_hat)

[[-0.05493422]
 [ 0.01529521]
 [-0.03181459]
 [-0.05762073]]


In [97]:
def forward_postproc(y_hat, y):
    diff = y_hat -y
    square = np.square(diff)
    loss = np.mean(square)
    
    return loss

In [98]:
loss = forward_postproc(y_hat, train_y)
print(loss)

70.32190183599843


In [99]:
def eval_accuracy(y_hat, y):
    mdiff = np.mean(np.abs((y_hat - y) / y))
    return 1 - mdiff

In [100]:
accuracy = eval_accuracy(y_hat, train_y)
print(f'accuracy : {accuracy:.3f}')

accuracy : -0.004


In [101]:
result = train_and_test(epoch_count=10,
                       mb_size = 2,
                       report = 2,
                       train_ratio = 0.8)

Epoch2: Train - Loss = 0.000, Accuracy = 95.000/Test - Accuracy = 100.000
Epoch4: Train - Loss = 0.000, Accuracy = 95.000/Test - Accuracy = 100.000
Epoch6: Train - Loss = 0.000, Accuracy = 95.000/Test - Accuracy = 100.000
Epoch8: Train - Loss = 0.000, Accuracy = 95.000/Test - Accuracy = 100.000
Epoch10: Train - Loss = 0.000, Accuracy = 95.000/Test - Accuracy = 100.000
============================== Final_TEST ==============================

 Final Accuracy: 100.000


In [102]:
def backprop_neuralnet(G_output, x):
    global weight, bias
    x_transpose = x.transpose()
    
    G_w = np.matmul(x_transpose , G_output)
    G_b = np.sum(G_output, axis = 0)
    
    weight -= LEARNING_RATE * G_w
    bias -= LEARNING_RATE * G_b
    

NameError: name 'X_train' is not defined